-- CREATE TABLE `errorreport` (
--   `ID` bigint(20) NOT NULL,
--   `CONTENT` varchar(255) DEFAULT NULL,
--   `RESOLVED` tinyint(1) DEFAULT '0',
--   `SENDINGDATE` varchar(255) DEFAULT NULL,
--   `myUser_id` bigint(20) DEFAULT NULL
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE ASD (
ID INT(11),
AGE VARCHAR(255)
);

-- CREATE TABLE ERRORREPORT (
-- ID INT NOT NULL AUTO_INCREMENT,
-- CONTENT TEXT DEFAULT NULL,
-- RESOLVED BOOL DEFAULT '0',
-- SENDINGDATE VARCHAR(255) DEFAULT NULL,
-- MYUSER_ID INT DEFAULT NULL,
-- PRIMARY KEY (ID)
-- #FOREIGN KEY (MYUSER_ID) REFERENCES MYUSER(ID)
-- );